---
title: "Installation"
from: markdown+emoji
---

::: {.callout-important appearance="simple"}
To follow the workshop, you should have the following programs installed on your machine ***before*** the day of the workshop.

- R and RStudio
- A few R packages
- Java JDK 21

See instructions below:
:::

# Installing R and RStudio

We assume you already have R and RStudio installed on your machine. In case you don't, [follow these simple instructions here](https://posit.co/download/rstudio-desktop/#download).



# Installing R packages

The workshop uses a few R packages that need to be installed on your machine. The simplest way to do this is running the code below. This might take a few minutes if this is the first time you install these packages.

```{R eval = FALSE, message = FALSE}
pkgs <- c(
  'r5r',
  'accessibility',
  'ggplot2',
  'mapview',
  'dplyr',
  'h3jsr',
  'sf'
  )

install.packages(pkgs)
```

The safest way to replicate the code of this workshop, though, is cloning its [repository](https://github.com/ipeaGIT/access_workshop_WSTLUR_2024) locally. This is because this repository uses the `{renv}` R package to manage the package dependencies of the code we use. This is important to make sure we are using the same versions of the relevant packages.

Once you have cloned the repo and you've opened the `access_workshop_bogota_2024.Rproj` file, you can simply run `renv::restore()` to install all the package dependencies used in this workshop.

```{R eval = FALSE}
# uncomment the line below in case you need to install the {renv} package
# install.packages('renv')
renv::restore()
```



# Installing Java

To use the `{r5r}` package (version v2.0 or higher), you will need to have *Java Development Kit (JDK) 21* installed on your computer. There are numerous open-source JDK implementations. The easiest way to install JDK is using the new [{rJavaEnv}](https://github.com/e-kotov/rJavaEnv) package in R, developed by Egor Kotov (thanks Egor!).

```{R eval = FALSE}
# install dev version of {rJavaEnv}
remotes::install_github("e-kotov/rJavaEnv")

# check version of Java currently installed (if any) 
rJavaEnv::java_check_version_rjava()

# install Java 21
rJavaEnv::java_quick_install(
  version = 21,
  distribution = 'Corretto')

# check if Java was successfully installed
rJavaEnv::java_check_version_rjava()
```

Alternatively, you can manually download and install any of these JDK implementations:

- [Adoptium/Eclipse Temurin](https://adoptium.net/)
- [Amazon Corretto](https://aws.amazon.com/corretto/)
- [Oracle OpenJDK](https://jdk.java.net/21/)


Here are a few accompanying slides explaining the computational requirements to conduct transport routing and accessibility analysis with `R`.

<p><embed src="slides/2_computational_requirements.pdf" style="width:100.0%;height:100vh;" /></p>

