project:
  type: website
  output-dir: docs

about:
  template: solana
  # links:
  #   - icon: twitter
  #     text: twitter
  #     href: https://x.com/UrbanDemog
  #   - icon: github
  #     text: Github
  #     href: https://github.com/ipeaGIT/access_workshop_WSTLUR_2024

execute:
  freeze: auto

lang: en
website:
  title: "A crash course on urban accessibility with R"
  favicon: /images/favicon.png
  site-url: https://ipeagit.github.io/access_workshop_bogota_2024/
  repo-url: https://github.com/ipeaGIT/access_workshop_bogota_2024
  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/ipeaGIT/access_workshop_WSTLUR_2024
      - icon: twitter
        text: twitter
        href: https://x.com/UrbanDemog
    contents:
      - index.qmd
      - section: "2. Getting started"
        contents:
          - href: 2.1_installation.qmd
          - href: 2.2_data_requirements.qmd
      - section: "3. Calculating accessibility"
        contents:
          - href: 3.1_quick_approach.qmd
          - href: 3.2_flexible_approach.qmd
          - href: 3.3_equity_measures.qmd

page-navigation: true
page-footer: 
  border: false
  left: "Copyright 2024, Rafael H. M. Pereira" 
  right: 
    - icon: github
      href: https://github.com/ipeaGIT/access_workshop_WSTLUR_2024


format:
  html:
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true

bibliography: references.bib

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

